# Generated by Django 5.2.8 on 2025-11-05 18:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banque",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_banque",
                    models.CharField(
                        help_text="Code unique de la banque (ex: ECOBANK, BGFI, CDCO)",
                        max_length=20,
                        unique=True,
                        verbose_name="Code banque",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                (
                    "nom_court",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nom court"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banques/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "couleur_primaire",
                    models.CharField(
                        default="#003366",
                        help_text="Format hexadécimal (ex: #003366)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format hexadécimal requis (ex: #FF5733)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Couleur primaire",
                    ),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(
                        default="#FF9900",
                        help_text="Format hexadécimal (ex: #FF9900)",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format hexadécimal requis (ex: #FF5733)",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "police_principale",
                    models.CharField(
                        default="Arial",
                        help_text="Nom de la police à utiliser dans les documents",
                        max_length=100,
                        verbose_name="Police principale",
                    ),
                ),
                (
                    "email_contact",
                    models.EmailField(max_length=254, verbose_name="Email de contact"),
                ),
                (
                    "telephone_contact",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "adresse",
                    models.TextField(blank=True, verbose_name="Adresse complète"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIF", "Actif"),
                            ("INACTIF", "Inactif"),
                            ("SUSPENDU", "Suspendu"),
                        ],
                        default="ACTIF",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_partenariat",
                    models.DateField(verbose_name="Date de partenariat"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "parametres_specifiques",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Paramètres personnalisés pour cette banque (commission, frais, etc.)",
                        verbose_name="Paramètres spécifiques",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banque",
                "verbose_name_plural": "Banques",
                "ordering": ["nom_complet"],
            },
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="banque",
            field=models.ForeignKey(
                blank=True,
                help_text="Banque de rattachement (obligatoire pour Responsable et Gestionnaire)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs",
                to="core.banque",
                verbose_name="Banque",
            ),
        ),
    ]
