# Generated by Django 5.2.8 on 2025-11-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_banque_utilisateur_banque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banque",
            name="date_partenariat",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de partenariat"
            ),
        ),
    ]
