# Generated by Django 5.2.8 on 2025-12-30 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_banque_date_partenariat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=200)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "banque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agences",
                        to="core.banque",
                    ),
                ),
                (
                    "responsable_agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agences_gerees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agence",
                "verbose_name_plural": "Agences",
                "db_table": "agences",
                "ordering": ["banque", "nom"],
                "unique_together": {("banque", "code")},
            },
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="agence",
            field=models.ForeignKey(
                blank=True,
                help_text="Agence à laquelle l'utilisateur est rattaché (pour Gestionnaires uniquement)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs",
                to="core.agence",
            ),
        ),
    ]
