# Generated by Django 5.2.8 on 2026-01-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ajouter_agences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="agence",
            field=models.ForeignKey(
                blank=True,
                help_text="Agence à laquelle l'utilisateur est rattaché (pour Responsable, Gestionnaires uniquement)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs",
                to="core.agence",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin NSIA"),
                    ("ADMIN_NSIA", "Admin NSIA"),
                    ("RESPONSABLE_BANQUE", "Responsable Banque"),
                    ("RESPONSABLE_AGENCE", "Responsable Agence"),
                    ("GESTIONNAIRE", "Gestionnaire"),
                    ("SUPPORT", "Support Technique"),
                ],
                default="GESTIONNAIRE",
                max_length=50,
                verbose_name="Rôle",
            ),
        ),
    ]
