# Generated by Django 5.2.8 on 2026-04-04 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_configure_express_union_emprunteur"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Hash du token",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_expiration", models.DateTimeField(verbose_name="Expire à")),
                (
                    "est_utilise",
                    models.BooleanField(default=False, verbose_name="Déjà utilisé"),
                ),
                (
                    "ip_demande",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP de la demande"
                    ),
                ),
                (
                    "ip_utilisation",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP d'utilisation"
                    ),
                ),
                (
                    "date_utilisation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'utilisation"
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de réinitialisation",
                "verbose_name_plural": "Tokens de réinitialisation",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(fields=["token_hash"], name="idx_token_hash"),
                    models.Index(
                        fields=["utilisateur", "est_utilise"],
                        name="idx_user_token_active",
                    ),
                ],
            },
        ),
    ]
