# Generated by Django 5.2.8 on 2026-04-16 07:13

import apps.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_loginattempt_security"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="core_logina_usernam_f4a0b6_idx",
            old_name="core_logina_usernam_idx",
        ),
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="core_logina_ip_addr_22e0ac_idx",
            old_name="core_logina_ip_addr_idx",
        ),
        migrations.AlterField(
            model_name="produitbanque",
            name="convention_pdf",
            field=models.FileField(
                blank=True,
                help_text="Fichier PDF de la convention pour ce produit/banque",
                null=True,
                upload_to="conventions/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    apps.core.models.validate_pdf_file,
                ],
                verbose_name="Convention PDF",
            ),
        ),
    ]
