# ============================================================
# Backend Django — Secret
# Identifiants PostgreSQL + Django Secret Key
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: nsia-backend
type: Opaque
stringData:
  POSTGRES_DB: "nsia_bancassurance"
  POSTGRES_USER: "nsia_user"
  POSTGRES_PASSWORD: "CHANGE_ME_VAULT_SECRET"
  DJANGO_SECRET_KEY: "CHANGE_ME_VAULT_SECRET"
  DJANGO_ALLOWED_HOSTS: "4.223.87.112,localhost"
  DB_NAME: "nsia_bancassurance"
  DB_USER: "nsia_user"
  DB_PASSWORD: "CHANGE_ME_VAULT_SECRET"
  SECRET_KEY: "CHANGE_ME_VAULT_SECRET"
  ALLOWED_HOSTS: "*"
