# Generated by Django 5.2.8 on 2025-11-07 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_alter_banque_date_partenariat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Ex: SIM-BGFI-20250106-001",
                        max_length=50,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "produit",
                    models.CharField(
                        choices=[
                            ("emprunteur", "Assurance Emprunteur"),
                            ("retraite", "Confort Retraite"),
                            ("etudes", "Confort Études"),
                            ("elikia", "Elikia Scolaire"),
                            ("mobateli", "Mobateli"),
                            ("epargne_plus", "Épargne Plus"),
                        ],
                        max_length=20,
                        verbose_name="Type de produit",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("calculee", "Calculée"),
                            ("validee", "Validée"),
                            ("convertie", "Convertie en souscription"),
                            ("abandonnee", "Abandonnée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "donnees_entree",
                    models.JSONField(
                        default=dict,
                        help_text="Inputs de l'utilisateur (montant, durée, âge...)",
                        verbose_name="Données d'entrée",
                    ),
                ),
                (
                    "resultats_calcul",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Outputs du calculateur (primes, taux...)",
                        verbose_name="Résultats du calcul",
                    ),
                ),
                (
                    "nom_client",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                (
                    "prenom_client",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                (
                    "email_client",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "telephone_client",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User Agent"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "banque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="core.banque",
                        verbose_name="Banque",
                    ),
                ),
                (
                    "gestionnaire",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulations_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gestionnaire créateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation",
                "verbose_name_plural": "Simulations",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Souscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Ex: SOUSCR-BGFI-20250106-001",
                        max_length=50,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours de traitement"),
                            ("validee", "Validée"),
                            ("rejetee", "Rejetée"),
                            ("suspendue", "Suspendue"),
                            ("active", "Active"),
                            ("resiliee", "Résiliée"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                (
                    "lieu_naissance",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Lieu de naissance"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                ("adresse", models.TextField(verbose_name="Adresse postale")),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profession"
                    ),
                ),
                (
                    "employeur",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Employeur"
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N° compte"
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Liste des documents fournis (CNI, justificatifs...)",
                        verbose_name="Documents attachés",
                    ),
                ),
                (
                    "numero_police",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Numéro de police",
                    ),
                ),
                (
                    "date_effet_contrat",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'effet du contrat"
                    ),
                ),
                (
                    "date_echeance_contrat",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance du contrat"
                    ),
                ),
                (
                    "montant_prime",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Montant de la prime (FCFA)",
                    ),
                ),
                (
                    "donnees_produit",
                    models.JSONField(
                        default=dict, verbose_name="Données spécifiques au produit"
                    ),
                ),
                (
                    "date_souscription",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de souscription"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "date_rejet",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de rejet"
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "commentaires",
                    models.TextField(blank=True, verbose_name="Commentaires"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "banque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="souscriptions",
                        to="core.banque",
                        verbose_name="Banque",
                    ),
                ),
                (
                    "gestionnaire",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="souscriptions_gerees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gestionnaire",
                    ),
                ),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="souscription",
                        to="simulateur.simulation",
                        verbose_name="Simulation d'origine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Souscription",
                "verbose_name_plural": "Souscriptions",
                "ordering": ["-date_souscription"],
            },
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["banque", "produit", "statut"],
                name="simulateur__banque__c68615_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["reference"], name="simulateur__referen_e6ad4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["gestionnaire", "-date_creation"],
                name="simulateur__gestion_be9311_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="simulation",
            index=models.Index(
                fields=["-date_creation"], name="simulateur__date_cr_e2506f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="souscription",
            index=models.Index(
                fields=["banque", "statut"], name="simulateur__banque__6b875b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="souscription",
            index=models.Index(
                fields=["reference"], name="simulateur__referen_f15fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="souscription",
            index=models.Index(
                fields=["numero_police"], name="simulateur__numero__a18c56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="souscription",
            index=models.Index(
                fields=["-date_souscription"], name="simulateur__date_so_a038d6_idx"
            ),
        ),
    ]
