# Generated by Django 5.2.8 on 2025-11-10 16:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_remplissage",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de remplissage"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "taille_cm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taille en centimètres (ex: 175.5)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("50")),
                            django.core.validators.MaxValueValidator(Decimal("250")),
                        ],
                        verbose_name="Taille (cm)",
                    ),
                ),
                (
                    "poids_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Poids en kilogrammes (ex: 75.5)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("20")),
                            django.core.validators.MaxValueValidator(Decimal("300")),
                        ],
                        verbose_name="Poids (kg)",
                    ),
                ),
                (
                    "imc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="Calculé automatiquement : poids / (taille^2)",
                        max_digits=4,
                        null=True,
                        verbose_name="IMC (Indice de Masse Corporelle)",
                    ),
                ),
                (
                    "tension_arterielle",
                    models.CharField(
                        blank=True,
                        help_text="Format: 120/80 (optionnel)",
                        max_length=20,
                        verbose_name="Tension artérielle",
                    ),
                ),
                ("fumeur", models.BooleanField(default=False, verbose_name="Fumeur")),
                (
                    "nb_cigarettes_jour",
                    models.IntegerField(
                        blank=True,
                        help_text="Si fumeur, indiquer le nombre (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Nombre de cigarettes par jour",
                    ),
                ),
                (
                    "consomme_alcool",
                    models.BooleanField(
                        default=False, verbose_name="Consomme de l'alcool régulièrement"
                    ),
                ),
                (
                    "distractions",
                    models.CharField(
                        blank=True,
                        help_text="Activités de loisirs (optionnel)",
                        max_length=200,
                        verbose_name="Distractions / Loisirs",
                    ),
                ),
                (
                    "pratique_sport",
                    models.BooleanField(
                        default=False, verbose_name="Pratique du sport"
                    ),
                ),
                (
                    "type_sport",
                    models.CharField(
                        blank=True,
                        help_text="Si sport, préciser lequel",
                        max_length=100,
                        verbose_name="Type de sport pratiqué",
                    ),
                ),
                (
                    "a_infirmite",
                    models.BooleanField(
                        default=False,
                        verbose_name="Êtes-vous atteint d'une infirmité ?",
                    ),
                ),
                (
                    "malade_6_derniers_mois",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avez-vous été malade au cours des 6 derniers mois ?",
                    ),
                ),
                (
                    "souvent_fatigue",
                    models.BooleanField(
                        default=False, verbose_name="Êtes-vous souvent fatigué(e) ?"
                    ),
                ),
                (
                    "perte_poids_recente",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avez-vous maigri depuis les 6 derniers mois ?",
                    ),
                ),
                (
                    "prise_poids_recente",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avez-vous grossi depuis les 6 derniers mois ?",
                    ),
                ),
                (
                    "a_ganglions",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avez-vous des ganglions, des furoncles, des abcès ou des maladies de la peau ?",
                    ),
                ),
                (
                    "fievre_persistante",
                    models.BooleanField(
                        default=False,
                        verbose_name="Toussez-vous depuis quelques temps avec en plus de la fièvre ?",
                    ),
                ),
                (
                    "plaies_buccales",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avez-vous des plaies dans la bouche ?",
                    ),
                ),
                (
                    "diarrhee_frequente",
                    models.BooleanField(
                        default=False, verbose_name="Faites-vous souvent la diarrhée ?"
                    ),
                ),
                (
                    "ballonnement",
                    models.BooleanField(
                        default=False, verbose_name="Êtes-vous souvent ballonné(e) ?"
                    ),
                ),
                (
                    "oedemes_membres_inferieurs",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avez-vous eu des œdèmes des Membres Inférieurs (O.M.I) ?",
                    ),
                ),
                (
                    "essoufflement",
                    models.BooleanField(
                        default=False,
                        verbose_name="Êtes-vous essoufflé(e) au moindre effort ?",
                    ),
                ),
                (
                    "a_eu_perfusion",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avez-vous déjà reçu une perfusion ?",
                    ),
                ),
                (
                    "a_eu_transfusion",
                    models.BooleanField(
                        default=False,
                        verbose_name="Avez-vous déjà reçu une transfusion de sang ?",
                    ),
                ),
                (
                    "infos_complementaires",
                    models.TextField(
                        blank=True,
                        help_text="Toute information médicale pertinente (optionnel)",
                        verbose_name="Informations complémentaires sur votre état de santé",
                    ),
                ),
                (
                    "score_risque",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        help_text="Points calculés automatiquement (0-30+)",
                        verbose_name="Score de risque",
                    ),
                ),
                (
                    "taux_surprime",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pourcentage de surprime calculé (0-20%)",
                        max_digits=5,
                        verbose_name="Taux de surprime (%)",
                    ),
                ),
                (
                    "categorie_risque",
                    models.CharField(
                        choices=[
                            ("FAIBLE", "Risque faible"),
                            ("MODERE", "Risque modéré"),
                            ("ELEVE", "Risque élevé"),
                            ("TRES_ELEVE", "Risque très élevé"),
                        ],
                        default="FAIBLE",
                        editable=False,
                        max_length=20,
                        verbose_name="Catégorie de risque",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente d'analyse"),
                            ("accepte", "Accepté"),
                            ("expertise_requise", "Expertise médicale requise"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut de validation",
                    ),
                ),
                (
                    "commentaire_medical",
                    models.TextField(
                        blank=True,
                        help_text="Remarques du validateur médical (si expertise requise)",
                        verbose_name="Commentaire médical",
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questionnaires_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "simulation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_medical",
                        to="simulateur.simulation",
                        verbose_name="Simulation liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Questionnaire médical",
                "verbose_name_plural": "Questionnaires médicaux",
                "db_table": "questionnaire_medical",
                "ordering": ["-date_remplissage"],
            },
        ),
    ]
