# Generated by Django 5.2.8 on 2025-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0002_questionnairemedical"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="adresse_postale",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="date_octroi",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="date_premiere_echeance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="employeur",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="numero_compte",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="profession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="situation_matrimoniale",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
