# Generated by Django 5.2.8 on 2025-12-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_agence_utilisateur_agence"),
        (
            "simulateur",
            "0003_simulation_adresse_postale_simulation_date_octroi_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="agence",
            field=models.ForeignKey(
                blank=True,
                help_text="Agence qui a créé la simulation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="simulations",
                to="core.agence",
            ),
        ),
    ]
