# Generated by Django 5.2.8 on 2025-12-30 13:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0004_simulation_agence"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="lieu_naissance",
            field=models.CharField(
                blank=True,
                help_text="Ville ou lieu de naissance",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="numero_convention",
            field=models.CharField(
                blank=True,
                help_text="Numéro de convention banque (ex: 1000359)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="taux_interet",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Taux d'intérêt du prêt en %",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="titre_assure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Monsieur"),
                    ("MME", "Madame"),
                    ("MLLE", "Mademoiselle"),
                ],
                help_text="Civilité de l'assuré",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="type_pret",
            field=models.CharField(
                choices=[
                    ("amortissement_standard", "Amortissement Standard"),
                    ("in_fine", "In Fine"),
                    ("progressif", "Progressif"),
                    ("libre", "Libre"),
                ],
                default="amortissement_standard",
                help_text="Type de remboursement du prêt",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Beneficiaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qualite",
                    models.CharField(
                        help_text="Qualité du bénéficiaire (ex: Organisme de prêt, Conjoint, Enfant)",
                        max_length=100,
                    ),
                ),
                (
                    "nom_prenoms",
                    models.CharField(
                        help_text="Nom complet du bénéficiaire", max_length=200
                    ),
                ),
                (
                    "part_pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Part du bénéficiaire en pourcentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=1, help_text="Ordre d'affichage du bénéficiaire"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "simulation",
                    models.ForeignKey(
                        help_text="Simulation à laquelle le bénéficiaire est rattaché",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaires",
                        to="simulateur.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bénéficiaire",
                "verbose_name_plural": "Bénéficiaires",
                "db_table": "beneficiaires",
                "ordering": ["simulation", "ordre"],
                "indexes": [
                    models.Index(
                        fields=["simulation"], name="beneficiair_simulat_bb3982_idx"
                    )
                ],
            },
        ),
    ]
