# Generated by Django 5.2.8 on 2025-12-30 13:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0004_simulation_agence"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="lieu_naissance",
            field=models.CharField(
                blank=True,
                help_text="Ville ou lieu de naissance",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="numero_convention",
            field=models.CharField(
                blank=True,
                help_text="Numéro de convention banque (ex: 1000359)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="taux_interet",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Taux d'intérêt du prêt en %",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="titre_assure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Monsieur"),
                    ("MME", "Madame"),
                    ("MLLE", "Mademoiselle"),
                ],
                help_text="Civilité de l'assuré",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="type_pret",
            field=models.CharField(
                choices=[
                    ("amortissement_standard", "Amortissement Standard"),
                    ("in_fine", "In Fine"),
                    ("progressif", "Progressif"),
                    ("libre", "Libre"),
                ],
                default="amortissement_standard",
                help_text="Type de remboursement du prêt",
                max_length=100,
            ),
        ),
    ]
