# Generated by Django 5.2.8 on 2025-12-31 10:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0005_simulation_lieu_naissance_and_more"),
    ]

    operations = [
        # ✅ CRÉER Beneficiaire (au lieu de le modifier)
        migrations.CreateModel(
            name="Beneficiaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "qualite",
                    models.CharField(
                        choices=[
                            ("organisme_pret", "Organisme de prêt"),
                            ("conjoint", "Conjoint"),
                            ("enfant", "Enfant"),
                            ("parent", "Parent"),
                            ("frere_soeur", "Frère/Sœur"),
                            ("autre", "Autre"),
                        ],
                        help_text="Relation du bénéficiaire avec l'assuré",
                        max_length=50,
                        verbose_name="En qualité de",
                    ),
                ),
                (
                    "nom_prenoms",
                    models.CharField(
                        help_text="Nom complet du bénéficiaire (ex: 'DUPONT Jean Pierre')",
                        max_length=200,
                        verbose_name="Nom et Prénoms",
                    ),
                ),
                (
                    "part_pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage de la garantie (ex: 100.00 pour 100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Part (%)",
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(
                        default=1,
                        help_text="Ordre d'affichage dans le BIA (1, 2, 3...)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiaires",
                        to="simulateur.simulation",
                        verbose_name="Simulation liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bénéficiaire",
                "verbose_name_plural": "Bénéficiaires",
                "db_table": "beneficiaires",
                "ordering": ["simulation", "ordre"],
            },
        ),
        # ✅ CRÉER DetailQ2 avec tous ses champs
        migrations.CreateModel(
            name="DetailQ2",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_field",
                    models.CharField(
                        help_text="Nom technique du champ (ex: 'a_infirmite', 'malade_6_derniers_mois')",
                        max_length=100,
                        verbose_name="Champ de la question",
                    ),
                ),
                (
                    "question_label",
                    models.CharField(
                        help_text="Texte de la question affichée (ex: 'Êtes-vous atteint d\\'une infirmité ?')",
                        max_length=200,
                        verbose_name="Libellé de la question",
                    ),
                ),
                (
                    "precisez",
                    models.TextField(
                        help_text="Nature exacte de l'affection/maladie (diagnostic)",
                        verbose_name="Précisez",
                    ),
                ),
                (
                    "periode_traitement",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 'Mars 2023 - en cours' ou 'Janvier 2024 - Février 2024'",
                        max_length=200,
                        verbose_name="Période du traitement",
                    ),
                ),
                (
                    "lieu_traitement",
                    models.CharField(
                        blank=True,
                        help_text="Hôpital/clinique où le traitement a eu lieu (ex: 'CHU de Brazzaville')",
                        max_length=200,
                        verbose_name="Lieu du traitement",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_medicaux",
                        to="simulateur.questionnairemedical",
                        verbose_name="Questionnaire lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail médical Q2",
                "verbose_name_plural": "Détails médicaux Q2",
                "db_table": "details_q2",
                "ordering": ["date_creation"],
                "unique_together": {("questionnaire", "question_field")},
            },
        ),
    ]