# Generated by Django 5.2.8 on 2026-01-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0007_alter_beneficiaire_qualite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiaire",
            name="qualite",
            field=models.CharField(
                choices=[
                    ("organisme_pret", "Organisme de prêt"),
                    ("conjoint", "Conjoint"),
                    ("enfant", "Enfant"),
                    ("parent", "Parent"),
                    ("frere_soeur", "Frère/Sœur"),
                    ("enfant_nee", "Enfant née"),
                    ("enfant_a_naitre", "Enfant à naitre"),
                    ("autre", "Autre"),
                    ("assure", "Assuré"),
                ],
                help_text="Relation du bénéficiaire avec l'assuré",
                max_length=50,
                verbose_name="En qualité de",
            ),
        ),
    ]
