# Generated by Django 5.2.8 on 2026-01-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0008_alter_beneficiaire_qualite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="produit",
            field=models.CharField(
                choices=[
                    ("emprunteur", "Assurance Emprunteur"),
                    ("retraite", "Confort Retraite"),
                    ("etudes", "Confort Études"),
                    ("elikia", "Elikia Scolaire"),
                    ("mobateli", "Mobateli"),
                    ("epargne_plus", "Épargne Plus"),
                    ("likama", "Likama BOA (DTC/IAD)"),
                ],
                max_length=20,
                verbose_name="Type de produit",
            ),
        ),
    ]
