# Generated by Django 5.2.8 on 2026-03-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0011_simulation_est_test"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="simulation",
            new_name="simulateur__est_tes_78c324_idx",
            old_name="simulateur_s_est_tes_idx",
        ),
    ]
