# Generated by Django 5.2.8 on 2026-03-28 15:07
# Modifiée : suppression de l'AlterField sur option_frais_funeraires
# (colonne supprimée dans 0013)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulateur", "0013_bia_mobateli_champs_complets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="lieu_naissance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
