# Generated by Django 5.2.8 on 2026-06-13 19:49

import apps.core.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulateur', '0014_alter_simulation_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='email_client_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='simulation',
            name='telephone_client_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='souscription',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='souscription',
            name='telephone_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='questionnairemedical',
            name='commentaire_medical',
            field=apps.core.security.EncryptedTextField(blank=True, help_text='Remarques du validateur médical (si expertise requise)', verbose_name='Commentaire médical'),
        ),
        migrations.AlterField(
            model_name='questionnairemedical',
            name='infos_complementaires',
            field=apps.core.security.EncryptedTextField(blank=True, help_text='Toute information médicale pertinente (optionnel)', verbose_name='Informations complémentaires sur votre état de santé'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='adresse_postale',
            field=apps.core.security.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='email_client',
            field=apps.core.security.EncryptedCharField(blank=True, max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='numero_compte',
            field=apps.core.security.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='N° compte'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='telephone_client',
            field=apps.core.security.EncryptedCharField(blank=True, max_length=255, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='adresse',
            field=apps.core.security.EncryptedTextField(verbose_name='Adresse postale'),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='email',
            field=apps.core.security.EncryptedCharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='numero_compte',
            field=apps.core.security.EncryptedCharField(blank=True, max_length=255, verbose_name='N° compte'),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='telephone',
            field=apps.core.security.EncryptedCharField(max_length=255, verbose_name='Téléphone'),
        ),
    ]
