# Generated by Django 5.2.8 on 2025-11-05 23:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_banque_utilisateur_banque"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableCIMA_H",
            fields=[
                (
                    "x",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="Âge (x)",
                    ),
                ),
                (
                    "Nx",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Nx"
                    ),
                ),
                (
                    "Mx",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Mx"
                    ),
                ),
                (
                    "Dx",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Dx"
                    ),
                ),
                (
                    "lx",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="lx"
                    ),
                ),
                (
                    "dxx",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="dxx"
                    ),
                ),
                (
                    "qx",
                    models.DecimalField(
                        decimal_places=10, max_digits=15, verbose_name="qx"
                    ),
                ),
                (
                    "Cx",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="Cx"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Table CIMA H",
                "verbose_name_plural": "Tables CIMA H",
                "ordering": ["x"],
            },
        ),
        migrations.CreateModel(
            name="TablePrimesEtudes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(70),
                        ],
                        verbose_name="Âge parent",
                    ),
                ),
                (
                    "duree_paiement",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Durée paiement (années)",
                    ),
                ),
                (
                    "duree_rente",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Durée rente (années)",
                    ),
                ),
                (
                    "type_prime",
                    models.CharField(
                        choices=[
                            ("ANNUELLE", "Prime Annuelle"),
                            ("UNIQUE", "Prime Unique"),
                        ],
                        max_length=20,
                        verbose_name="Type de prime",
                    ),
                ),
                (
                    "produit",
                    models.CharField(
                        choices=[
                            ("100k", "100 000 FCFA"),
                            ("200k", "200 000 FCFA"),
                            ("300k", "300 000 FCFA"),
                            ("500k", "500 000 FCFA"),
                            ("750k", "750 000 FCFA"),
                            ("1M", "1 000 000 FCFA"),
                            ("1.5M", "1 500 000 FCFA"),
                            ("2M", "2 000 000 FCFA"),
                            ("2.5M", "2 500 000 FCFA"),
                            ("3M", "3 000 000 FCFA"),
                        ],
                        max_length=10,
                        verbose_name="Produit (Rente)",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant prime"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prime Études",
                "verbose_name_plural": "Primes Études",
                "ordering": ["age", "duree_paiement", "type_prime"],
                "indexes": [
                    models.Index(
                        fields=["age", "duree_paiement", "duree_rente", "produit"],
                        name="tarificatio_age_7b5d03_idx",
                    )
                ],
                "unique_together": {
                    ("age", "duree_paiement", "duree_rente", "type_prime", "produit")
                },
            },
        ),
        migrations.CreateModel(
            name="TableTauxMensuels",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(70),
                        ],
                        verbose_name="Âge parent",
                    ),
                ),
                (
                    "duree_paiement",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Durée paiement (années)",
                    ),
                ),
                (
                    "duree_rente",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="Durée rente (années)",
                    ),
                ),
                (
                    "produit",
                    models.CharField(
                        default="NSIA-ETUDES", max_length=50, verbose_name="Produit"
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        decimal_places=8, max_digits=10, verbose_name="Taux mensuel"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Taux Mensuel",
                "verbose_name_plural": "Taux Mensuels",
                "ordering": ["age", "duree_paiement"],
                "indexes": [
                    models.Index(
                        fields=["age", "duree_paiement", "duree_rente"],
                        name="tarificatio_age_05eb47_idx",
                    )
                ],
                "unique_together": {
                    ("age", "duree_paiement", "duree_rente", "produit")
                },
            },
        ),
        migrations.CreateModel(
            name="ParametresProduits",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "produit_type",
                    models.CharField(
                        choices=[
                            ("emprunteur", "Emprunteur (ADI)"),
                            ("retraite", "Confort Retraite"),
                            ("etudes", "Confort Études"),
                            ("elikia", "Elikia Scolaire"),
                            ("mobateli", "Mobateli"),
                            ("epargne_plus", "Épargne Plus"),
                        ],
                        max_length=50,
                        verbose_name="Type de produit",
                    ),
                ),
                (
                    "param_nom",
                    models.CharField(
                        help_text="Ex: taux_interet_technique",
                        max_length=100,
                        verbose_name="Nom du paramètre",
                    ),
                ),
                (
                    "param_valeur",
                    models.CharField(max_length=255, verbose_name="Valeur"),
                ),
                (
                    "type_valeur",
                    models.CharField(
                        choices=[
                            ("decimal", "Décimal"),
                            ("string", "Texte"),
                            ("boolean", "Booléen"),
                            ("integer", "Entier"),
                        ],
                        default="decimal",
                        max_length=20,
                        verbose_name="Type de valeur",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "banque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametres_produits",
                        to="core.banque",
                        verbose_name="Banque spécifique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre Produit",
                "verbose_name_plural": "Paramètres Produits",
                "ordering": ["produit_type", "param_nom"],
                "unique_together": {("produit_type", "param_nom", "banque")},
            },
        ),
        migrations.CreateModel(
            name="TableTauxEmprunteur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tranche_age",
                    models.CharField(
                        help_text="Ex: 29-39",
                        max_length=20,
                        verbose_name="Tranche d'âge",
                    ),
                ),
                (
                    "age_min",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "age_max",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "duree_annees",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="Durée (années)",
                    ),
                ),
                (
                    "taux_pourcentage",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Ex: 0.370 pour 0.37%",
                        max_digits=5,
                        verbose_name="Taux (%)",
                    ),
                ),
                (
                    "produit",
                    models.CharField(
                        default="emprunteur",
                        help_text="emprunteur ou epargne_plus",
                        max_length=50,
                        verbose_name="Produit",
                    ),
                ),
                (
                    "date_debut_validite",
                    models.DateField(verbose_name="Date début validité"),
                ),
                (
                    "date_fin_validite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date fin validité"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "banque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taux_emprunteur",
                        to="core.banque",
                        verbose_name="Banque spécifique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taux Emprunteur",
                "verbose_name_plural": "Taux Emprunteur",
                "ordering": ["age_min", "duree_annees"],
                "indexes": [
                    models.Index(
                        fields=["age_min", "age_max", "duree_annees"],
                        name="tarificatio_age_min_c7d27a_idx",
                    ),
                    models.Index(
                        fields=["produit", "actif"],
                        name="tarificatio_produit_0eb2cf_idx",
                    ),
                ],
            },
        ),
    ]
