# Generated by Django 5.2.8 on 2025-11-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableCIMA_F",
            fields=[
                (
                    "x",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Âge"
                    ),
                ),
                (
                    "lx",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="lx - Survivants"
                    ),
                ),
                (
                    "dxx",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="dx - Décès"
                    ),
                ),
                (
                    "qx",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=10,
                        verbose_name="qx - Probabilité décès",
                    ),
                ),
                (
                    "Dx",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Dx - Valeur actualisée survivants",
                    ),
                ),
                (
                    "Nx",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Nx - Somme Dx"
                    ),
                ),
                (
                    "Cx",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Cx - Valeur actualisée décès",
                    ),
                ),
                (
                    "Mx",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Mx - Somme Cx"
                    ),
                ),
            ],
            options={
                "verbose_name": "Table CIMA Femmes",
                "verbose_name_plural": "Tables CIMA Femmes",
                "db_table": "simulateur_cima_f",
            },
        ),
    ]
