# Generated by Django 5.2.8 on 2025-11-06 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_banque_utilisateur_banque"),
        ("tarification", "0002_tablecima_f"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tabletauxemprunteur",
            options={
                "ordering": ["age_min", "duree_annees", "duree_mois"],
                "verbose_name": "Taux Emprunteur",
                "verbose_name_plural": "Taux Emprunteur",
            },
        ),
        migrations.RemoveIndex(
            model_name="tabletauxemprunteur",
            name="tarificatio_age_min_c7d27a_idx",
        ),
        migrations.RemoveIndex(
            model_name="tabletauxemprunteur",
            name="tarificatio_produit_0eb2cf_idx",
        ),
        migrations.AddField(
            model_name="tabletauxemprunteur",
            name="duree_mois",
            field=models.IntegerField(
                blank=True,
                help_text="Laisser vide si durée en années",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(360),
                ],
                verbose_name="Durée (mois)",
            ),
        ),
        migrations.AddField(
            model_name="tabletauxemprunteur",
            name="frais_accessoires",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Frais forfaitaires selon convention",
                max_digits=10,
                verbose_name="Frais accessoires (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="tabletauxemprunteur",
            name="duree_annees",
            field=models.IntegerField(
                blank=True,
                help_text="Laisser vide si durée en mois",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Durée (années)",
            ),
        ),
        migrations.AlterField(
            model_name="tabletauxemprunteur",
            name="produit",
            field=models.CharField(
                default="emprunteur",
                help_text="emprunteur, epargne_plus, etc.",
                max_length=50,
                verbose_name="Produit",
            ),
        ),
        migrations.AlterField(
            model_name="tabletauxemprunteur",
            name="taux_pourcentage",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Ex: 0.370 pour 0.37%",
                max_digits=6,
                verbose_name="Taux (%)",
            ),
        ),
        migrations.AddIndex(
            model_name="tabletauxemprunteur",
            index=models.Index(
                fields=["age_min", "age_max", "duree_annees", "duree_mois"],
                name="tarificatio_age_min_ba426e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tabletauxemprunteur",
            index=models.Index(
                fields=["produit", "actif", "banque"],
                name="tarificatio_produit_ffb68f_idx",
            ),
        ),
    ]
