# Generated by Django 5.2.8 on 2025-11-06 17:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_banque_utilisateur_banque"),
        ("tarification", "0003_alter_tabletauxemprunteur_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TablePrimesElikia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rente_annuelle",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ex: 200000, 400000, 600000...",
                        max_digits=10,
                        verbose_name="Rente annuelle (FCFA)",
                    ),
                ),
                (
                    "duree_rente",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Durée de rente (années)",
                    ),
                ),
                (
                    "capital_garanti",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Capital garanti (FCFA)",
                    ),
                ),
                (
                    "tranche_age",
                    models.CharField(
                        help_text="Ex: 45 ans et moins, 46-55 ans, 56-64 ans",
                        max_length=30,
                        verbose_name="Tranche d'âge",
                    ),
                ),
                (
                    "age_min",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(70),
                        ]
                    ),
                ),
                (
                    "age_max",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(70),
                        ]
                    ),
                ),
                (
                    "prime_nette_annuelle",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prime nette annuelle (FCFA)",
                    ),
                ),
                (
                    "date_debut_validite",
                    models.DateField(verbose_name="Date début validité"),
                ),
                (
                    "date_fin_validite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date fin validité"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "banque",
                    models.ForeignKey(
                        limit_choices_to={"code": "BCI"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primes_elikia",
                        to="core.banque",
                        verbose_name="Banque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prime Elikia Scolaire",
                "verbose_name_plural": "Primes Elikia Scolaire",
                "ordering": ["rente_annuelle", "age_min"],
                "indexes": [
                    models.Index(
                        fields=["rente_annuelle", "age_min", "age_max"],
                        name="tarificatio_rente_a_6b54ca_idx",
                    ),
                    models.Index(
                        fields=["banque", "actif"],
                        name="tarificatio_banque__fcc1b5_idx",
                    ),
                ],
                "unique_together": {
                    ("banque", "rente_annuelle", "duree_rente", "age_min", "age_max")
                },
            },
        ),
        migrations.CreateModel(
            name="TablePrimesMobateli",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capital_dtc_iad",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ex: 2000000, 5000000, 7500000",
                        max_digits=12,
                        verbose_name="Capital DTC/IAD (FCFA)",
                    ),
                ),
                (
                    "tranche_age",
                    models.CharField(
                        help_text="Ex: Moins de 45 ans, 45-54 ans, 55-64 ans",
                        max_length=30,
                        verbose_name="Tranche d'âge",
                    ),
                ),
                (
                    "age_min",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(70),
                        ]
                    ),
                ),
                (
                    "age_max",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(70),
                        ]
                    ),
                ),
                (
                    "prime_nette",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prime nette (FCFA)",
                    ),
                ),
                (
                    "date_debut_validite",
                    models.DateField(verbose_name="Date début validité"),
                ),
                (
                    "date_fin_validite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date fin validité"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "banque",
                    models.ForeignKey(
                        limit_choices_to={"code": "BCI"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primes_mobateli",
                        to="core.banque",
                        verbose_name="Banque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prime Mobateli",
                "verbose_name_plural": "Primes Mobateli",
                "ordering": ["capital_dtc_iad", "age_min"],
                "indexes": [
                    models.Index(
                        fields=["capital_dtc_iad", "age_min", "age_max"],
                        name="tarificatio_capital_bcbed3_idx",
                    ),
                    models.Index(
                        fields=["banque", "actif"],
                        name="tarificatio_banque__6df452_idx",
                    ),
                ],
                "unique_together": {
                    ("banque", "capital_dtc_iad", "age_min", "age_max")
                },
            },
        ),
    ]
