# Generated by Django 5.2.8 on 2026-01-17 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ajouter_agences"),
        ("tarification", "0004_tableprimeselikia_tableprimesmobateli"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableLikamaBOA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "capital_dtc_iad",
                    models.IntegerField(
                        help_text="Montant du capital assuré (ex: 2000000, 5000000, 7500000)",
                        verbose_name="Capital DTC/IAD",
                    ),
                ),
                (
                    "tranche_age",
                    models.CharField(
                        help_text="Ex: 'Moins de 45 ans', 'de 45 à 54 ans', 'de 55 à 64 ans'",
                        max_length=50,
                        verbose_name="Tranche d'âge",
                    ),
                ),
                (
                    "age_min",
                    models.IntegerField(
                        help_text="Âge minimum de la tranche (inclus)",
                        verbose_name="Âge minimum",
                    ),
                ),
                (
                    "age_max",
                    models.IntegerField(
                        help_text="Âge maximum de la tranche (inclus)",
                        verbose_name="Âge maximum",
                    ),
                ),
                (
                    "prime",
                    models.IntegerField(
                        help_text="Prime nette d'assurance en FCFA",
                        verbose_name="Prime nette",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Tarif actuellement utilisable",
                        verbose_name="Tarif actif",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "banque",
                    models.ForeignKey(
                        limit_choices_to={"code": "BOA"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primes_likama",
                        to="core.banque",
                        verbose_name="Banque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif Likama BOA",
                "verbose_name_plural": "Tarifs Likama BOA",
                "db_table": "tarification_tablelikamaboa",
                "ordering": ["capital_dtc_iad", "age_min"],
                "indexes": [
                    models.Index(
                        fields=["capital_dtc_iad", "age_min"],
                        name="tarificatio_capital_5a5715_idx",
                    ),
                    models.Index(fields=["actif"], name="tarificatio_actif_3907ac_idx"),
                ],
                "unique_together": {("capital_dtc_iad", "age_min", "age_max")},
            },
        ),
    ]
