# Generated by Django 5.2.8 on 2026-01-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarification", "0005_tablelikamaboa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableprimesmobateli",
            name="date_debut_validite",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date début validité"
            ),
        ),
    ]
