# Generated by Django 5.2.8 on 2026-01-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarification", "0006_alter_tableprimesmobateli_date_debut_validite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableprimeselikia",
            name="date_debut_validite",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date début validité"
            ),
        ),
        migrations.AlterField(
            model_name="tabletauxemprunteur",
            name="date_debut_validite",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date début validité"
            ),
        ),
    ]
