# Generated by Django 5.2.8 on 2026-01-18 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ajouter_agences"),
        ("tarification", "0007_alter_tableprimeselikia_date_debut_validite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableprimeselikia",
            name="banque",
            field=models.ForeignKey(
                limit_choices_to={"code": ["BCI", "BOA"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primes_elikia",
                to="core.banque",
                verbose_name="Banque",
            ),
        ),
        migrations.AlterField(
            model_name="tableprimesmobateli",
            name="banque",
            field=models.ForeignKey(
                limit_choices_to={"code": ["BCI", "BOA"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primes_mobateli",
                to="core.banque",
                verbose_name="Banque",
            ),
        ),
    ]
