# Generated by Django 5.2.8 on 2026-01-23 17:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_utilisateur_agence_alter_utilisateur_role"),
        ("tarification", "0008_alter_tableprimeselikia_banque_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableEpargnePlus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "taux_interet_annuel",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.030400"),
                        help_text="Taux d'intérêt annuel (ex: 0.0304 pour 3.04%)",
                        max_digits=6,
                        verbose_name="Taux d'intérêt annuel",
                    ),
                ),
                (
                    "taux_interet_mensuel",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.002499"),
                        help_text="Taux d'intérêt mensuel (calculé à partir du taux annuel)",
                        max_digits=6,
                        verbose_name="Taux d'intérêt mensuel",
                    ),
                ),
                (
                    "frais_adhesion",
                    models.IntegerField(
                        default=5000,
                        help_text="Frais d'adhésion uniques en FCFA",
                        verbose_name="Frais d'adhésion",
                    ),
                ),
                (
                    "taux_frais_gestion",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0300"),
                        help_text="Frais de gestion sur chaque prime (ex: 0.03 pour 3%)",
                        max_digits=5,
                        verbose_name="Taux frais de gestion",
                    ),
                ),
                (
                    "taux_frais_acquisition",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0300"),
                        help_text="Frais d'acquisition sur chaque prime (ex: 0.03 pour 3%)",
                        max_digits=5,
                        verbose_name="Taux frais d'acquisition",
                    ),
                ),
                (
                    "taux_frais_tirage",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0100"),
                        help_text="Frais de tirage sur chaque prime (ex: 0.01 pour 1%)",
                        max_digits=5,
                        verbose_name="Taux frais de tirage",
                    ),
                ),
                (
                    "taux_penalite_rachat",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0500"),
                        help_text="Pénalité en cas de rachat anticipé (ex: 0.05 pour 5%)",
                        max_digits=5,
                        verbose_name="Taux pénalité rachat anticipé",
                    ),
                ),
                (
                    "cotisation_minimum",
                    models.IntegerField(
                        default=5000,
                        help_text="Cotisation mensuelle minimum en FCFA",
                        verbose_name="Cotisation minimum",
                    ),
                ),
                (
                    "duree_minimum_annees",
                    models.IntegerField(
                        default=5,
                        help_text="Durée minimum du contrat en années",
                        verbose_name="Durée minimum en années",
                    ),
                ),
                (
                    "duree_penalite_annees",
                    models.IntegerField(
                        default=10,
                        help_text="Durée en années avant laquelle une pénalité s'applique en cas de rachat",
                        verbose_name="Durée pénalité en années",
                    ),
                ),
                (
                    "periodicite_tirage",
                    models.CharField(
                        default="Trimestriel",
                        help_text="Périodicité des tirages au sort (ex: Trimestriel)",
                        max_length=20,
                        verbose_name="Périodicité des tirages",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Paramètres actifs"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "banque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tables_epargne_plus",
                        to="core.banque",
                        verbose_name="Banque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres Épargne Plus",
                "verbose_name_plural": "Paramètres Épargne Plus",
                "db_table": "simulateur_table_epargne_plus",
                "ordering": ["banque__nom_court"],
                "indexes": [
                    models.Index(
                        fields=["banque", "actif"],
                        name="simulateur__banque__f7c933_idx",
                    )
                ],
                "unique_together": {("banque",)},
            },
        ),
        migrations.CreateModel(
            name="TableParametresEpargnePlus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "taux_interet_annuel",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.0304"),
                        help_text="Taux d'intérêt annuel (ex: 0.0304 = 3.04%)",
                        max_digits=6,
                        verbose_name="Taux d'intérêt annuel",
                    ),
                ),
                (
                    "taux_interet_mensuel",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Taux d'intérêt mensuel calculé automatiquement",
                        max_digits=8,
                        null=True,
                        verbose_name="Taux d'intérêt mensuel",
                    ),
                ),
                (
                    "taux_frais_gestion",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0300"),
                        help_text="Frais de gestion sur prime (ex: 0.03 = 3%)",
                        max_digits=5,
                        verbose_name="Taux frais de gestion",
                    ),
                ),
                (
                    "taux_frais_acquisition",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0300"),
                        help_text="Frais d'acquisition sur prime (ex: 0.03 = 3%)",
                        max_digits=5,
                        verbose_name="Taux frais d'acquisition",
                    ),
                ),
                (
                    "taux_frais_tirage",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0100"),
                        help_text="Frais de tirage sur prime (ex: 0.01 = 1%)",
                        max_digits=5,
                        verbose_name="Taux frais de tirage",
                    ),
                ),
                (
                    "taux_frais_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Somme des frais (calculé automatiquement)",
                        max_digits=5,
                        null=True,
                        verbose_name="Taux frais total",
                    ),
                ),
                (
                    "frais_adhesion_minimum",
                    models.IntegerField(
                        default=5000,
                        help_text="Frais d'adhésion en FCFA",
                        verbose_name="Frais d'adhésion minimum",
                    ),
                ),
                (
                    "cotisation_minimum",
                    models.IntegerField(
                        default=5000,
                        help_text="Cotisation mensuelle minimum en FCFA",
                        verbose_name="Cotisation minimum",
                    ),
                ),
                (
                    "duree_minimum_annees",
                    models.IntegerField(
                        default=5,
                        help_text="Durée minimum du contrat en années",
                        verbose_name="Durée minimum en années",
                    ),
                ),
                (
                    "duree_penalite_rachat_annees",
                    models.IntegerField(
                        default=10,
                        help_text="Durée maximale de pénalité de rachat en années",
                        verbose_name="Durée pénalité rachat",
                    ),
                ),
                (
                    "taux_penalite_rachat",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0500"),
                        help_text="Pénalité de rachat anticipé (ex: 0.05 = 5%)",
                        max_digits=5,
                        verbose_name="Taux pénalité rachat",
                    ),
                ),
                (
                    "periodicite",
                    models.CharField(
                        default="Mensuel",
                        help_text="Périodicité des cotisations (Mensuel, Trimestriel, etc.)",
                        max_length=20,
                        verbose_name="Périodicité",
                    ),
                ),
                (
                    "periodicite_tirage",
                    models.CharField(
                        default="Trimestriel",
                        help_text="Périodicité des tirages",
                        max_length=20,
                        verbose_name="Périodicité tirages",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Paramètres actifs"),
                ),
                (
                    "delai_minimum_rachat_mois",
                    models.IntegerField(
                        default=12,
                        help_text="Nombre de mois minimum avant rachat (BGFI : 12 mois)",
                        verbose_name="Délai minimum rachat (mois)",
                    ),
                ),
                (
                    "rachat_partiel_max_12_23_mois",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="BGFI : 50% entre 12 et 23 mois",
                        max_digits=5,
                        verbose_name="Rachat partiel max 12-23 mois (%)",
                    ),
                ),
                (
                    "rachat_partiel_max_24_plus_mois",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("85.00"),
                        help_text="BGFI : 85% à partir de 24 mois",
                        max_digits=5,
                        verbose_name="Rachat partiel max 24+ mois (%)",
                    ),
                ),
                (
                    "taux_quote_part_tirage",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0100"),
                        help_text="BGFI : 1% pour fonds cagnotte",
                        max_digits=5,
                        verbose_name="Quote-part tirage au sort",
                    ),
                ),
                (
                    "cotisation_exceptionnelle_minimum_multiplicateur",
                    models.IntegerField(
                        default=2,
                        help_text="BGFI : Minimum = 2× cotisation mensuelle",
                        verbose_name="Multiplicateur cotisation exceptionnelle",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "banque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parametres_epargne_plus",
                        to="core.banque",
                        verbose_name="Banque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres Épargne Plus",
                "verbose_name_plural": "Paramètres Épargne Plus",
                "db_table": "tarification_parametres_epargne_plus",
                "ordering": ["banque__nom_court"],
                "indexes": [
                    models.Index(
                        fields=["banque"], name="tarificatio_banque__034f28_idx"
                    ),
                    models.Index(fields=["actif"], name="tarificatio_actif_608d93_idx"),
                ],
                "unique_together": {("banque",)},
            },
        ),
    ]
