# Generated by Django 5.2.8 on 2026-02-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_utilisateur_agence_alter_utilisateur_role"),
        ("tarification", "0009_tableepargneplus_tableparametresepargneplus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableprimeselikia",
            name="banque",
            field=models.ForeignKey(
                limit_choices_to={"code": ["BCI", "BOA", "COMIFI"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primes_elikia",
                to="core.banque",
                verbose_name="Banque",
            ),
        ),
    ]
