# Generated by Django 5.2.8 on 2026-03-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_utilisateur_agence_alter_utilisateur_role"),
        ("tarification", "0012_alter_tableprimeselikia_banque_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tableprimeselikia",
            name="banque",
            field=models.ForeignKey(
                limit_choices_to={
                    "code": ["BCI", "BOA", "COMIFI", "COFINCO", "EXPRESS_UNION"]
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primes_elikia",
                to="core.banque",
                verbose_name="Banque",
            ),
        ),
        migrations.AlterField(
            model_name="tableprimesmobateli",
            name="banque",
            field=models.ForeignKey(
                limit_choices_to={
                    "code": ["BCI", "BOA", "COMIFI", "COFINCO", "EXPRESS_UNION"]
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primes_mobateli",
                to="core.banque",
                verbose_name="Banque",
            ),
        ),
    ]
