# Generated by Django 5.2.8 on 2026-03-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarification", "0014_dynamic_limit_choices_to"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TableLikamaBOA",
        ),
    ]
