apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix-mail-service
  namespace: nsia-security
  labels:
    app: postfix-mail-service
    nsia.cg/component: mail-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix-mail-service
  template:
    metadata:
      labels:
        app: postfix-mail-service
        nsia.cg/component: mail-relay
    spec:
      containers:
        - name: mailpit
          image: axllent/mailpit:latest
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
